---
- name: Edu provision
  hosts: edu
  roles:
    - { role: simple-role, tags: [role] }
  tasks:
    - name: Shell testing
      shell: date
    - debug:
        var: test_var
    - debug:
        var: test_var2

